<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::connection('tenant')->create('product_settings', function (Blueprint $t) { $t->id(); $t->boolean('manages_collections')->default(false); $t->boolean('manages_collection_lines')->default(false); $t->timestamps(); });
        Schema::connection('tenant')->create('product_attributes', function (Blueprint $t) { $t->id(); $t->string('code',50)->unique(); $t->string('name',100); $t->boolean('is_enabled')->default(false); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); });
        Schema::connection('tenant')->create('product_attribute_values', function (Blueprint $t) { $t->id(); $t->foreignId('product_attribute_id')->constrained('product_attributes')->cascadeOnDelete(); $t->string('value',100); $t->string('normalized_value',120); $t->boolean('is_active')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['product_attribute_id','normalized_value']); });
        Schema::connection('tenant')->create('product_categories', function (Blueprint $t) { $t->id(); $t->foreignId('parent_id')->nullable()->constrained('product_categories')->nullOnDelete(); $t->unsignedBigInteger('parent_key')->default(0); $t->string('name',150); $t->string('normalized_name',170); $t->string('slug',180); $t->text('description')->nullable(); $t->boolean('is_active')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['parent_key','normalized_name']); $t->unique('slug'); });
        Schema::connection('tenant')->create('product_collections', function (Blueprint $t) { $t->id(); $t->string('name',150); $t->string('normalized_name',170)->unique(); $t->string('reference',100)->nullable()->index(); $t->text('description')->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::connection('tenant')->create('product_collection_lines', function (Blueprint $t) { $t->id(); $t->foreignId('product_collection_id')->constrained('product_collections')->cascadeOnDelete(); $t->string('name',150); $t->string('normalized_name',170); $t->text('description')->nullable(); $t->boolean('is_active')->default(true); $t->unsignedInteger('sort_order')->default(0); $t->timestamps(); $t->unique(['product_collection_id','normalized_name']); });
        Schema::connection('tenant')->create('products', function (Blueprint $t) { $t->id(); $t->string('catalog_code',120)->nullable()->index(); $t->string('name',200); $t->text('description')->nullable(); $t->foreignId('category_id')->nullable()->constrained('product_categories')->nullOnDelete(); $t->foreignId('product_collection_id')->nullable()->constrained('product_collections')->nullOnDelete(); $t->foreignId('product_collection_line_id')->nullable()->constrained('product_collection_lines')->nullOnDelete(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::connection('tenant')->create('product_variants', function (Blueprint $t) { $t->id(); $t->foreignId('product_id')->constrained('products')->cascadeOnDelete(); $t->string('sku',150)->unique(); $t->string('auxiliary_code',150)->nullable()->index(); $t->decimal('stock',14,3)->nullable(); $t->decimal('minimum_stock',14,3)->nullable(); $t->decimal('sale_price',14,4)->nullable(); $t->decimal('purchase_price',14,4)->nullable(); $t->boolean('is_for_sale')->default(true); $t->boolean('is_for_purchase')->default(false); $t->boolean('is_taxable')->default(true); $t->decimal('tax_rate',8,4)->nullable(); $t->boolean('is_active')->default(true); $t->timestamps(); });
        Schema::connection('tenant')->create('product_variant_attribute_value', function (Blueprint $t) { $t->foreignId('product_variant_id')->constrained('product_variants')->cascadeOnDelete(); $t->foreignId('product_attribute_value_id')->constrained('product_attribute_values')->cascadeOnDelete(); $t->primary(['product_variant_id','product_attribute_value_id']); });
    }
    public function down(): void { foreach (['product_variant_attribute_value','product_variants','products','product_collection_lines','product_collections','product_categories','product_attribute_values','product_attributes','product_settings'] as $table) Schema::connection('tenant')->dropIfExists($table); }
};
