<x-layouts.tenant title="Horarios" subtitle="Planificación mensual de asignaciones">
    <div id="schedule-calendar" data-events-url="{{ route('operations.schedule.events') }}" data-store-url="{{ route('operations.assignments.store') }}" data-update-url="{{ route('operations.assignments.update', '__ASSIGNMENT__') }}" data-delete-url="{{ route('operations.assignments.destroy', '__ASSIGNMENT__') }}" data-store-admin="{{ $scope['role'] === 'store_admin' ? '1' : '0' }}">
        <div class="tr-card mb-3">
            <div class="d-flex align-items-center justify-content-between mb-3"><h2 class="h6 mb-0">Filtros</h2><button class="btn btn-sm btn-outline-secondary" type="button" data-calendar-reset>Limpiar</button></div>
            <div class="row g-3">
                <div class="col-md-4"><label class="form-label" for="filter-branch">Sucursal</label><select class="form-select" id="filter-branch" data-calendar-filter="branch_id" @disabled($scope['role'] === 'store_admin')>@if ($scope['role'] === 'management')<option value="">Todas las sucursales</option>@endif @foreach ($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="form-label" for="filter-user">Colaborador</label><select class="form-select" id="filter-user" data-calendar-filter="core_user_id"><option value="">Todos los colaboradores</option>@foreach ($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div>
                <div class="col-md-4"><label class="form-label" for="filter-shift">Turno</label><select class="form-select" id="filter-shift" data-calendar-filter="shift_id"><option value="">Todos los turnos</option>@foreach ($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->name }}</option>@endforeach</select></div>
            </div>
        </div>
        <div class="tr-card"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h6 mb-1">Calendario de asignaciones</h2><p class="text-muted small mb-0">Haz clic en un día para crear una asignación o en un evento para editarlo.</p></div><button class="btn btn-primary" type="button" data-calendar-new><i data-lucide="plus" class="me-1"></i>Nueva asignación</button></div><div data-calendar-canvas></div></div>

        <div class="modal fade" id="assignment-modal" tabindex="-1" aria-hidden="true"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form id="assignment-form" novalidate><div class="modal-header"><h2 class="modal-title fs-5" data-modal-title>Nueva asignación</h2><button class="btn-close" type="button" data-bs-dismiss="modal" aria-label="Cerrar"></button></div><div class="modal-body"><div class="mb-3"><label class="form-label" for="assignment-date">Fecha</label><input class="form-control" id="assignment-date" name="date" type="date" required></div><div class="mb-3"><label class="form-label" for="assignment-user">Colaborador</label><select class="form-select" id="assignment-user" name="core_user_id" required>@foreach ($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></div><div class="mb-3"><label class="form-label" for="assignment-branch">Sucursal</label><select class="form-select" id="assignment-branch" name="branch_id" required @disabled($scope['role'] === 'store_admin')>@foreach ($branches as $branch)<option value="{{ $branch->id }}">{{ $branch->name }}</option>@endforeach</select><div class="form-text" @if ($scope['role'] !== 'store_admin') hidden @endif>Tu sucursal está fijada por tu perfil operativo.</div></div><div class="mb-0"><label class="form-label" for="assignment-shift">Turno</label><select class="form-select" id="assignment-shift" name="shift_id" required>@foreach ($shifts as $shift)<option value="{{ $shift->id }}">{{ $shift->name }}</option>@endforeach</select></div><div class="alert alert-danger d-none mt-3 mb-0" role="alert" data-calendar-error></div></div><div class="modal-footer"><button class="btn btn-outline-danger me-auto d-none" type="button" data-calendar-delete>Eliminar</button><button class="btn btn-light" type="button" data-bs-dismiss="modal">Cancelar</button><button class="btn btn-primary" type="submit">Guardar</button></div></form></div></div></div>
    </div>

    @push('page-scripts')
        @vite(['resources/js/pages/operations-schedule.js'])
    @endpush
</x-layouts.tenant>
