@php($editing = isset($checklist))
<x-layouts.tenant title="{{ $editing ? 'Editar checklist' : 'Nuevo checklist' }}" subtitle="Plantilla operativa por uno o varios turnos">
    <div class="tr-card"><form method="POST" action="{{ $editing ? route('checklists.update',$checklist) : route('checklists.store') }}" id="checklist-form">@csrf @if($editing) @method('PUT') @endif
        <div class="row g-3"><div class="col-md-7"><label class="form-label">Nombre</label><input class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name',$checklist->name ?? '') }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-5"><label class="form-label">Estado</label><select class="form-select" name="status"><option value="active" @selected(old('status',$checklist->status ?? 'active') === 'active')>Activo</option><option value="inactive" @selected(old('status',$checklist->status ?? '') === 'inactive')>Inactivo</option></select></div><div class="col-12"><label class="form-label">Descripción</label><textarea class="form-control" rows="3" name="description">{{ old('description',$checklist->description ?? '') }}</textarea></div><div class="col-12"><label class="form-label">Turnos asociados</label><div class="row g-2">@foreach($shifts as $shift)<div class="col-md-4"><label class="form-check border rounded p-3 w-100"><input class="form-check-input me-2" type="checkbox" name="shift_ids[]" value="{{ $shift->id }}" @checked(in_array($shift->id, old('shift_ids', $editing ? $checklist->shifts->pluck('id')->all() : [])))>{{ $shift->name }} <span class="text-muted small">{{ substr($shift->start_time,0,5) }}–{{ substr($shift->end_time,0,5) }}</span></label></div>@endforeach</div>@error('shift_ids')<div class="text-danger small mt-1">{{ $message }}</div>@enderror</div></div>
        <hr class="my-4"><div class="d-flex align-items-center justify-content-between mb-3"><div><h5 class="mb-1">Tareas del checklist</h5><p class="text-muted small mb-0">Arrastra las filas para reordenarlas. El orden se guarda al guardar el checklist.</p></div><button class="btn btn-outline-primary" type="button" data-add-checklist-item><i data-lucide="plus" class="me-1"></i>Agregar tarea</button></div>
        <div class="alert alert-info">Cada tarea requiere hora de inicio y hora límite. No se usa numeración manual.</div>
        <div class="table-responsive"><table class="table table-custom align-middle"><thead><tr><th></th><th>Tarea</th><th>Inicio</th><th>Hora límite</th><th></th></tr></thead><tbody data-checklist-items>
            @foreach(old('items', $editing ? $checklist->items->map(fn($item) => ['id'=>$item->id,'task_id'=>$item->task_id,'start_time'=>substr((string)$item->start_time,0,5),'due_time'=>substr((string)$item->due_time,0,5)])->all() : []) as $index => $item)
                <tr draggable="true" data-checklist-item><td class="text-muted" data-drag-handle title="Arrastrar">⠿<input type="hidden" name="items[{{ $index }}][id]" value="{{ $item['id'] ?? '' }}"></td><td><select class="form-select" name="items[{{ $index }}][task_id]" required><option value="">Selecciona una tarea</option>@foreach($tasks as $task)<option value="{{ $task->id }}" @selected((string)$item['task_id'] === (string)$task->id)>{{ $task->name }}{{ $task->status === 'inactive' ? ' (inactiva)' : '' }}</option>@endforeach</select></td><td><input class="form-control" type="time" name="items[{{ $index }}][start_time]" value="{{ $item['start_time'] ?? '' }}" required></td><td><input class="form-control" type="time" name="items[{{ $index }}][due_time]" value="{{ $item['due_time'] ?? '' }}" required></td><td class="text-end"><button class="btn btn-sm btn-light text-danger" type="button" data-remove-checklist-item><i data-lucide="trash-2"></i></button></td></tr>
            @endforeach
        </tbody></table></div>
        @error('items')<div class="text-danger small">{{ $message }}</div>@enderror
        <div class="d-flex gap-2 mt-4"><button class="btn btn-primary">Guardar checklist</button><a class="btn btn-light" href="{{ $editing ? route('checklists.show',$checklist) : route('checklists.index') }}">Cancelar</a></div>
    </form></div>
    <template id="checklist-item-template"><tr draggable="true" data-checklist-item><td class="text-muted" data-drag-handle title="Arrastrar">⠿<input type="hidden" data-field="id"></td><td><select class="form-select" data-field="task_id" required><option value="">Selecciona una tarea</option>@foreach($tasks as $task)<option value="{{ $task->id }}">{{ $task->name }}{{ $task->status === 'inactive' ? ' (inactiva)' : '' }}</option>@endforeach</select></td><td><input class="form-control" type="time" data-field="start_time" required></td><td><input class="form-control" type="time" data-field="due_time" required></td><td class="text-end"><button class="btn btn-sm btn-light text-danger" type="button" data-remove-checklist-item><i data-lucide="trash-2"></i></button></td></tr></template>
    @push('page-scripts')@vite(['resources/js/pages/checklist-editor.js'])@endpush
</x-layouts.tenant>
