@props(['title' => "Core Admin · Today's Retail"])
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" data-bs-theme="light">
    <head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $title }}</title>@vite(['resources/scss/todays-retail.scss', 'resources/js/todays-retail.js'])</head>
    <body><div class="app-shell">
        <header class="app-topbar"><a class="brand-link" href="{{ route('admin.accounts.index') }}"><span class="brand-mark">TR</span><span>Today's Retail</span></a><button class="topbar-button" type="button" data-sidenav-toggle aria-label="Mostrar u ocultar menú"><i data-lucide="menu"></i></button><div class="topbar-account"><span>Administración interna</span><strong>Core Admin</strong></div><div class="topbar-actions"><a class="topbar-button" href="{{ route('dashboard') }}" aria-label="Volver al dashboard"><i data-lucide="arrow-left"></i></a><button class="topbar-button" type="button" data-theme-toggle aria-label="Cambiar tema"><i data-lucide="moon"></i></button></div></header>
        <aside class="app-sidebar"><div class="sidebar-scroll" data-simplebar><p class="sidebar-heading">Core Admin</p><ul class="side-nav"><li class="side-nav-item"><a class="side-nav-link {{ request()->routeIs('admin.accounts.*') ? 'active' : '' }}" href="{{ route('admin.accounts.index') }}"><i data-lucide="building-2"></i><span>Cuentas</span></a></li><li class="side-nav-item"><a class="side-nav-link {{ request()->routeIs('admin.users.*') ? 'active' : '' }}" href="{{ route('admin.users.index') }}"><i data-lucide="users-round"></i><span>Usuarios</span></a></li><li class="side-nav-item"><a class="side-nav-link {{ request()->routeIs('admin.roles.*') ? 'active' : '' }}" href="{{ route('admin.roles.index') }}"><i data-lucide="shield-check"></i><span>Roles</span></a></li></ul></div></aside>
        <main class="content-page"><div class="content-container"><div class="page-title-box"><div><h1>{{ $title }}</h1><p>Administración interna de Today's Retail</p></div></div>@if (session('success'))<div class="tr-notice">{{ session('success') }}</div>@endif{{ $slot }}</div><footer class="app-footer">© {{ now()->year }} Today's Retail · Core Admin</footer></main>
    </div></body>
</html>
